
version: '3.8'
services:
  postgres: 
    image: postgres
    restart: 'always'
    ports:
      - "54322:5432"
    environment:
      - DATABASE_HOST=${HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}